#ifndef __SIMCOM_A7682E_GPIO_H__
#define __SIMCOM_A7682E_GPIO_H__

typedef enum
{
    SC_MODULE_GPIO_1 = 1,
    SC_MODULE_GPIO_2 = 2,
    SC_MODULE_GPIO_3 = 3,

    SC_MODULE_GPIO_6 = 6,
    SC_MODULE_GPIO_7 = 7,
    SC_MODULE_GPIO_8 = 8,
    SC_MODULE_GPIO_9 = 9,
    SC_MODULE_GPIO_10 = 10,
    SC_MODULE_GPIO_11 = 11,
    SC_MODULE_GPIO_12 = 12,
    SC_MODULE_GPIO_13 = 13,
    SC_MODULE_GPIO_14 = 14,
    SC_MODULE_GPIO_MAX

}SC_Module_GPIONumbers;
#endif
